-- CreateTable
CREATE TABLE `alumnos` (
    `id_alumno` INTEGER NOT NULL AUTO_INCREMENT,
    `control_al` INTEGER NOT NULL,
    `folio_al` INTEGER NOT NULL,
    `nombre` TEXT NOT NULL,
    `apellidoPaterno` TEXT NOT NULL,
    `apellidoMaterno` TEXT NOT NULL,
    `genero` TEXT NOT NULL,
    `curp` TEXT NOT NULL,
    `fechaNacimiento` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `nacionalidad` TEXT NOT NULL,
    `lugarNacimiento` TEXT NOT NULL,
    `estadoCivil` TEXT NOT NULL,
    `tieneHijos` BOOLEAN NOT NULL,
    `cuantosHijos` TEXT NOT NULL,
    `calle` TEXT NOT NULL,
    `numeroExterior` TEXT NOT NULL,
    `numeroInterior` TEXT NOT NULL,
    `colonia` TEXT NOT NULL,
    `codigoPostal` TEXT NOT NULL,
    `telefonoCasa` TEXT NOT NULL,
    `telefonoCelular` TEXT NOT NULL,
    `correo` TEXT NOT NULL,
    `nombrePadre` TEXT NOT NULL,
    `padreVive` BOOLEAN NOT NULL,
    `fechaPadre` DATE NOT NULL,
    `nacionalidadPadre` TEXT NOT NULL,
    `lugarNacimientoPadre` TEXT NOT NULL,
    `curpPadre` TEXT NOT NULL,
    `gradoEstudiosPadre` TEXT NOT NULL,
    `telefonoCasaPadre` TEXT NOT NULL,
    `telefonoCelularPadre` TEXT NOT NULL,
    `viveContigoPadre` BOOLEAN NOT NULL,
    `domicilioPadre` TEXT NOT NULL,
    `trabajaPadre` BOOLEAN NOT NULL,
    `ocupacionPadre` TEXT NOT NULL,
    `lugarTrabajoPadre` TEXT NOT NULL,
    `ingresosPadre` TEXT NOT NULL,
    `nombreMadre` TEXT NOT NULL,
    `madreVive` BOOLEAN NOT NULL,
    `fechaMadre` DATE NOT NULL,
    `nacionalidadMadre` TEXT NOT NULL,
    `lugarNacimientoMadre` TEXT NOT NULL,
    `curpMadre` TEXT NOT NULL,
    `gradoEstudiosMadre` TEXT NOT NULL,
    `telefonoCasaMadre` TEXT NOT NULL,
    `telefonoCelularMadre` TEXT NOT NULL,
    `viveContigoMadre` BOOLEAN NOT NULL,
    `domicilioMadre` TEXT NOT NULL,
    `trabajaMadre` BOOLEAN NOT NULL,
    `ocupacionMadre` TEXT NOT NULL,
    `lugarTrabajoMadre` TEXT NOT NULL,
    `ingresosMadre` TEXT NOT NULL,
    `tutor` TEXT NOT NULL,
    `casa` TEXT NOT NULL,
    `tipoCasa` TEXT NOT NULL,
    `tipoParedes` TEXT NOT NULL,
    `piso` TEXT NOT NULL,
    `tipoTecho` TEXT NOT NULL,
    `aguaPotable` BOOLEAN NOT NULL,
    `drenaje` BOOLEAN NOT NULL,
    `electricidad` BOOLEAN NOT NULL,
    `lavadora` BOOLEAN NOT NULL,
    `estufaGas` BOOLEAN NOT NULL,
    `hornoMicroondas` BOOLEAN NOT NULL,
    `refrigerador` BOOLEAN NOT NULL,
    `lineaTelefonica` BOOLEAN NOT NULL,
    `computadoraEscritorio` BOOLEAN NOT NULL,
    `laptop` BOOLEAN NOT NULL,
    `tableta` BOOLEAN NOT NULL,
    `internet` BOOLEAN NOT NULL,
    `televisionPaga` BOOLEAN NOT NULL,
    `secadora` BOOLEAN NOT NULL,
    `tabletaPersonal` BOOLEAN NOT NULL,
    `laptopPersonal` BOOLEAN NOT NULL,
    `smartphonePersonal` BOOLEAN NOT NULL,
    `focosCasa` TEXT NOT NULL,
    `televisionesCasa` TEXT NOT NULL,
    `pertenecesGrupoIndigena` BOOLEAN NOT NULL,
    `cualGrupoIndigena` TEXT NOT NULL,
    `trabajasActualmente` BOOLEAN NOT NULL,
    `nombreEmpresa` TEXT NOT NULL,
    `cargoEmpresa` TEXT NOT NULL,
    `ubicacionEmpresa` TEXT NOT NULL,
    `telefonoEmpresa` TEXT NOT NULL,
    `trabajoHorarioInicio` TEXT NOT NULL,
    `trabajoHorarioFin` TEXT NOT NULL,
    `tuIngresoMensual` TEXT NOT NULL,
    `casaInternet` BOOLEAN NOT NULL,
    `cafeInternet` BOOLEAN NOT NULL,
    `escuelaInternet` BOOLEAN NOT NULL,
    `casaAmigoInternet` BOOLEAN NOT NULL,
    `trabajoInternet` BOOLEAN NOT NULL,
    `otroLugarInternet` BOOLEAN NOT NULL,
    `usoInternetJugar` BOOLEAN NOT NULL,
    `usoInternetEmail` BOOLEAN NOT NULL,
    `usoInternetBancaLinea` BOOLEAN NOT NULL,
    `usoInternetRS` BOOLEAN NOT NULL,
    `usoInternetBuscarAmigos` BOOLEAN NOT NULL,
    `usoInternetForosDiscusion` BOOLEAN NOT NULL,
    `usoInternetNoticias` BOOLEAN NOT NULL,
    `usoInternetVideos` BOOLEAN NOT NULL,
    `usoInternetInfo` BOOLEAN NOT NULL,
    `usoInternetSoftware` BOOLEAN NOT NULL,
    `usoInternetPeliculas` BOOLEAN NOT NULL,
    `usoInternetMusica` BOOLEAN NOT NULL,
    `usoInternetEmpleo` BOOLEAN NOT NULL,
    `usoInternetPareja` BOOLEAN NOT NULL,
    `usoInternetCompras` BOOLEAN NOT NULL,
    `usoInternetLlamadas` BOOLEAN NOT NULL,
    `usoInternetPaginaAdultos` BOOLEAN NOT NULL,
    `tienesEmail` BOOLEAN NOT NULL,
    `tienesYoutube` BOOLEAN NOT NULL,
    `tienesRedSocial` BOOLEAN NOT NULL,
    `usoComunicacion` BOOLEAN NOT NULL,
    `usoAmistad` BOOLEAN NOT NULL,
    `usoBuscarAmigos` BOOLEAN NOT NULL,
    `usoRelacionesProfesionales` BOOLEAN NOT NULL,
    `usoBuscarPareja` BOOLEAN NOT NULL,
    `usoEntretenimiento` BOOLEAN NOT NULL,
    `usoTrabajoEscolares` BOOLEAN NOT NULL,
    `usoIntercambiarInfo` BOOLEAN NOT NULL,
    `usoOtros` BOOLEAN NOT NULL,
    `figuraFisica` TEXT NOT NULL,
    `estatura` INTEGER NOT NULL,
    `peso` DOUBLE NOT NULL,
    `problemaSalud` BOOLEAN NOT NULL,
    `tipoProblemaSalud` TEXT NOT NULL,
    `numSeguro` TEXT NOT NULL,
    `serviciosMedicos` TEXT NOT NULL,
    `otroServicioMedico` TEXT NOT NULL,
    `frecuenciaMedico` TEXT NOT NULL,
    `frecuenciaDentista` TEXT NOT NULL,
    `necesitasLentes` TEXT NOT NULL,
    `discapacidadMotriz` BOOLEAN NOT NULL,
    `discapacidadAuditiva` BOOLEAN NOT NULL,
    `discapacidadVisual` BOOLEAN NOT NULL,
    `discapacidadIntelectual` BOOLEAN NOT NULL,
    `discapacidadOtra` BOOLEAN NOT NULL,
    `discapacidadOtraEspecifica` TEXT NOT NULL,
    `tratamientoMental` BOOLEAN NOT NULL,
    `asistenciaTratamientoMental` TEXT NOT NULL,
    `tienesAlergia` BOOLEAN NOT NULL,
    `tiposAlergias` TEXT NOT NULL,
    `especificaAlergias` TEXT NOT NULL,
    `problemasCorazon` BOOLEAN NOT NULL,
    `tratamientoCorazon` BOOLEAN NOT NULL,
    `problemasEpilepsia` BOOLEAN NOT NULL,
    `tratamientoEpilepsia` BOOLEAN NOT NULL,
    `problemasAsma` BOOLEAN NOT NULL,
    `tratamientoAsma` BOOLEAN NOT NULL,
    `problemasVertigo` BOOLEAN NOT NULL,
    `tratamientoVertigo` BOOLEAN NOT NULL,
    `problemasMigrana` BOOLEAN NOT NULL,
    `tratamientoMigrana` BOOLEAN NOT NULL,
    `otroTratamientoMedico` BOOLEAN NOT NULL,
    `especificaOtroTratamientoMedico` TEXT NOT NULL,
    `vacunadoCovid` BOOLEAN NOT NULL,
    `numVacunasCovid` INTEGER NOT NULL,
    `ultimaVacunaCovid` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `transtornoGastrointestinal` TEXT NOT NULL,
    `transtornoRespiratorio` TEXT NOT NULL,
    `transtornoCirculatorio` TEXT NOT NULL,
    `transtornoPiel` TEXT NOT NULL,
    `transtornoNeurologico` TEXT NOT NULL,
    `transtornoGenitourinario` TEXT NOT NULL,
    `frecuenciaDesayuno` TEXT NOT NULL,
    `frecuenciaComes` TEXT NOT NULL,
    `frecuenciaCenas` TEXT NOT NULL,
    `consumirFrutas` TEXT NOT NULL,
    `consumirVerduras` TEXT NOT NULL,
    `consumirCereales` TEXT NOT NULL,
    `consumirTuberculos` TEXT NOT NULL,
    `consumirLacteos` TEXT NOT NULL,
    `consumirLeguminosas` TEXT NOT NULL,
    `consumirCarneRoja` TEXT NOT NULL,
    `consumirCarneBlanca` TEXT NOT NULL,
    `consumirSodas` TEXT NOT NULL,
    `consumirJugosNaturalesEnvasados` TEXT NOT NULL,
    `consumirGolosinas` TEXT NOT NULL,
    `consumirGolosinasSaladas` TEXT NOT NULL,
    `consumirComidaRapida` TEXT NOT NULL,
    `consumirPanDulce` TEXT NOT NULL,
    `consumirPanBlanco` TEXT NOT NULL,
    `consumirTortillas` TEXT NOT NULL,
    `vecesSemanaEjercicio` TEXT NOT NULL,
    `practicasFutbol` BOOLEAN NOT NULL,
    `practicasTenis` BOOLEAN NOT NULL,
    `practicasBoxeo` BOOLEAN NOT NULL,
    `practicasBeisbol` BOOLEAN NOT NULL,
    `practicasGimnasia` BOOLEAN NOT NULL,
    `practicasLucha` BOOLEAN NOT NULL,
    `practicasBasquetbol` BOOLEAN NOT NULL,
    `practicasJudo` BOOLEAN NOT NULL,
    `practicasCiclismo` BOOLEAN NOT NULL,
    `practicasNatacion` BOOLEAN NOT NULL,
    `practicasKarate` BOOLEAN NOT NULL,
    `practicasCharreria` BOOLEAN NOT NULL,
    `practicasAtletismo` BOOLEAN NOT NULL,
    `practicasHalterofilia` BOOLEAN NOT NULL,
    `practicasOtro` BOOLEAN NOT NULL,
    `irParque` BOOLEAN NOT NULL,
    `irCine` BOOLEAN NOT NULL,
    `irBailar` BOOLEAN NOT NULL,
    `jugarVideojuegos` BOOLEAN NOT NULL,
    `hacerDeporte` BOOLEAN NOT NULL,
    `reunirteAmigos` BOOLEAN NOT NULL,
    `salirPareja` BOOLEAN NOT NULL,
    `escucharMusica` BOOLEAN NOT NULL,
    `usarComputadora` BOOLEAN NOT NULL,
    `verTV` BOOLEAN NOT NULL,
    `verPeliculas` BOOLEAN NOT NULL,
    `leer` BOOLEAN NOT NULL,
    `otrasActividades` BOOLEAN NOT NULL,
    `especificaOtrasActividades` TEXT NOT NULL,
    `buenaComunicacionPadres` TEXT NOT NULL,
    `existeBuenaComunicacionPadres` TEXT NOT NULL,
    `faltasReglasHogarCorrectivo` TEXT NOT NULL,
    `maltratoMiembroFamilia` TEXT NOT NULL,
    `participasDecisionesHogar` TEXT NOT NULL,
    `padresInteresActividadesEscolares` TEXT NOT NULL,
    `fumas` BOOLEAN NOT NULL,
    `frecuenciaFumas` TEXT NOT NULL,
    `consumesCerveza` BOOLEAN NOT NULL,
    `frecuenciaCerveza` TEXT NOT NULL,
    `consumesLicores` BOOLEAN NOT NULL,
    `frecuenciaLicores` TEXT NOT NULL,
    `consumesVinos` BOOLEAN NOT NULL,
    `frecuenciaVinos` TEXT NOT NULL,
    `consumesDrogas` BOOLEAN NOT NULL,
    `tipoDroga` TEXT NOT NULL,
    `opcionUnoCarrera` VARCHAR(191) NOT NULL,
    `opcionDosCarrera` VARCHAR(191) NOT NULL,
    `opcionTresCarrera` VARCHAR(191) NOT NULL,
    `tienesBeca` BOOLEAN NOT NULL,
    `tipoBeca` TEXT NOT NULL,
    `especificaBeca` TEXT NOT NULL,
    `clubFutbol` BOOLEAN NOT NULL,
    `clubBasquetbol` BOOLEAN NOT NULL,
    `clubBeisbol` BOOLEAN NOT NULL,
    `clubVoleybol` BOOLEAN NOT NULL,
    `clubAtletismo` BOOLEAN NOT NULL,
    `clubBandaGuerra` BOOLEAN NOT NULL,
    `clubDanza` BOOLEAN NOT NULL,
    `clubEscolta` BOOLEAN NOT NULL,
    `clubRondalla` BOOLEAN NOT NULL,
    `clubRobotica` BOOLEAN NOT NULL,
    `clubCinematografia` BOOLEAN NOT NULL,
    `clubPeriodismo` BOOLEAN NOT NULL,
    `clubPorras` BOOLEAN NOT NULL,
    `certificadoSecundaria` TEXT NOT NULL,
    `actaNacimiento` TEXT NOT NULL,
    `curpArchivo` TEXT NOT NULL,
    `formatoFM3` TEXT NOT NULL,

    PRIMARY KEY (`id_alumno`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `carreras` (
    `id_carrera` INTEGER NOT NULL AUTO_INCREMENT,
    `carreraNombre` INTEGER NOT NULL,

    PRIMARY KEY (`id_carrera`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `familiares` (
    `id_familiar` INTEGER NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(100) NOT NULL,
    `parentesco` VARCHAR(100) NOT NULL,
    `ocupacion` VARCHAR(100) NOT NULL,
    `edad` INTEGER NOT NULL,
    `ingreso` VARCHAR(100) NOT NULL,
    `celular` VARCHAR(30) NOT NULL,
    `id_alumno` INTEGER NOT NULL,
    `key` VARCHAR(100) NOT NULL,

    INDEX `id_alumno`(`id_alumno`),
    PRIMARY KEY (`id_familiar`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `talleres` (
    `id_taller` INTEGER NOT NULL AUTO_INCREMENT,
    `nombreTaller` VARCHAR(50) NOT NULL,

    PRIMARY KEY (`id_taller`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `talleres_seleccionados_alumnos` (
    `id_alumno` INTEGER NOT NULL,
    `id_taller` INTEGER NOT NULL,

    INDEX `id_alumno`(`id_alumno`),
    INDEX `id_taller`(`id_taller`),
    PRIMARY KEY (`id_alumno`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `familiares` ADD CONSTRAINT `familiares_ibfk_1` FOREIGN KEY (`id_alumno`) REFERENCES `alumnos`(`id_alumno`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `talleres_seleccionados_alumnos` ADD CONSTRAINT `talleres_seleccionados_alumnos_ibfk_1` FOREIGN KEY (`id_alumno`) REFERENCES `alumnos`(`id_alumno`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `talleres_seleccionados_alumnos` ADD CONSTRAINT `talleres_seleccionados_alumnos_ibfk_2` FOREIGN KEY (`id_taller`) REFERENCES `talleres`(`id_taller`) ON DELETE RESTRICT ON UPDATE RESTRICT;
